
[build]
  command = "pip install -r requirements.txt && mkdir -p functions && cp app.py functions/app.py"
  publish = "."
  functions = "functions"


[[redirects]]
from = "/*"
to = "/.netlify/functions/app"
status = 200
